version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: kedu-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kedu_payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
